mer-hybris/droid-hal-device

device-lge-mako-configs/lib/systemd/system/bluetooth.service.wants/hcismd.service, device-lge-mako-configs/lib/systemd/system/hcismd.service, device-lge-mako-configs/sbin/hcismd-enable.sh
This needs CONFIG_BT_HCISMD=y in the kernel.  For some reason, writing to the sysfs files using tmpfiles.d at boot doesn't work - you need to wait some amount of time before writing to the file.
=> [mako] Enable Bluetooth HCI SMD during boot.

droid-hal-device.inc
Sometimes hardware vendors add custom features to the default android
image creation tools in their BSPs, or the BSP requires a specific
version of those tools. Added option "enable_device_specific_tools"
that can be set 1 in device specific spec file to build a custom
droid-hal-tools specific to that device BSP instead of using the default
droid-hal-tools.
=> [tools] Add option for building device specific droid-hal-tools

droid-hal-device.inc, helpers/img2simg.mk, helpers/makefile, helpers/mkbootimg.mk, helpers/simg2img.mk
This reverts commit f6bf842884bd5dfa458dd8b2b868337fc2c78d6f.
If device specific tools are needed, one should just modify a
device specific droid-hal-tools package for their adaptation.
It is much quicker and works better with legacy functionality.
=> Revert "[tools] Add option for device specific image creation tools"

droid-hal-device.inc
Some adaptations might need to have their own post scripts that are device specific, lets allow this by adding macro for it.
Signed-off-by: Marko Saukko <marko.saukko@jolla.com>
=> Add possibility to add post scripts via rpm macro.

helpers/img2simg.mk, helpers/simg2img.mk
The output_file.c source uses too smart macro magics for it's own good,
which doesn't play well with C99. Disabled -std=c99 option for
img2simg to make it build without errors. Same added for simg2img
as it builds against same object files.
=> [tools] Fix img2simg build. Fixes JB#28015

droid-hal-@DEVICE@.spec.template, droid-hal-device.inc, helpers/add_new_device.sh, helpers/amibehind.sh, helpers/build_packages.sh, helpers/util.sh
=> Add template for the upcoming migration script

droid-hal-device.inc
HADK dhd builds that still use RPM upload to OBS, should still have rel_date
timestamp as release, and therefore should define local_hadk_build_project
macro (currently provisioned under /usr/lib/rpm/macros.d/)
All OBS builds (including QA checkers) should not have local_hadk_build_project
macro defined.
=> do timestamped releases only for local HADK builds

droid-hal-device.inc
To be able to have post dhd build packaged recovery images, it
should be possible to disable recovery image generation from
droid-hal-device. Added option "have_custom_img_boot" for this.
[dhd] Allow having custom recovery image. Fixes NEMO#836
=> Allow having custom recovery image

device-lge-mako-configs/etc/pulse/arm_qct_apq8064_mako.pa
Trying to load module-bluetooth-discover with bluez4 discover module
arguments causes bluez5-discover module loading to fail, which causes
whole module loading to fail. Until module-bluetooth-discover is fixed
to pass only bluez-specific arguments to the discovery modules, just
load module-bluez4-discover directly.
=> [mako][pulseaudio] Load BlueZ4 discovery module.

droid-hal-device.inc
In order to get better trackability for kernel, append
+<dhd version> to kernel EXTRAVERSION when we do OBS based builds.
E.g. a previously "3.10.20" versioned kernel will turn into something
like "3.10.20+0.0.6-1".
The code checks also linux/kernel folder in case normal kernel/ folder
does not contain a Makefile. This is to be compatible with Intel android
trees.
=> [kernel] Add kernel EXTRAVERSION appending for OBS builds.

droid-hal-device.inc
Device tree is coming with new ARM devices. With this change we package
to kernel package the dt.img binary if it exists.
=> [kernel] Add devicetree image to kernel if it exists.

droid-hal-device.inc
Many Qualcomm devices (but not all) use QCOM_BSP which requires a definition in android-config.h for libhybris and qt5-qpa-hwcomposer-plugin to work. This has caused a lot of confusion and problems for new porters so let's try to automate the detection of QCOM_BSP by grepping the BoardConfig*.mk files in device tree.
=> [dhd] Add automatic detection of QCOM_BSP.

device-lge-mako-configs/var/lib/environment/compositor/droid-hal-device.conf, patterns/mako/jolla-hw-adaptation-mako.yaml
since mako inverted the ui the value must be changed to zero. added additional pattern entries for cellular packages and geoclue-provider-hybris-community
Change-Id: I35e463fef8440a16189e256053e782b78574970b
=> [mako] modified patterns for cellular functionaliy and disabled the ui inversion

droid-hal-device.inc
Remove kernel modules from droid-hal-device if those are installed under %{device}/system/modules. Modules are installed already on kernel modules package.
=> Remove kernel modules from droid-hal-device rpm

helpers/build_packages.sh
Needed for GPS to work in applications.
=> [build_packages] Add geoclue-providers-hybris.

helpers/extract-headers.sh
Fixes building for Android 6.0 based devices.
=> Fix audio header extraction on Android 6.0 based builds.

helpers/util.sh
Variable PORT_ARCH replaced ARCH in .hadk.env a long time ago and should also be fixed here.
=> [build_packages] Fix build for non-armv7hl ports.

helpers/build_packages.sh
Fix URL for sensorfw which has moved to https://git.merproject.org/mer-core/sensorfw.git.
=> [build_packages] sensorfw has moved to git.merproject.org.

helpers/build_packages.sh
=> [build_packages] Use qt-5.2 branch of qt5-qpa-hwcomposer-plugin until Qt 5.6 is available.

helpers/makefstab
This fixes issues encountered on several ports having dashes in mount point names. Adding also escaping for some other possible special characters.
=> [mkfstab] Escape some special characters from mount unit names.

helpers/util.sh
Otherwise, if rebuilt, it doesn't get pulled in automatically, due to Version: always staying the same on local builds
=> Always install a build package on target

droid-hal-device.inc
Mounting functionfs to /dev/usb-ffs/adb as done by Android will break MTP in Sailfish OS so let's skip that mountpoint to make MTP work again. This problem appeared after https://github.com/mer-hybris/droid-hal-device/commit/dd9ce1e4ce9ff76726894341e0775a9e86b8e003 fixed the mountpoint name and the mount started to work. At least Fairphone 2 and OnePlus X were affected.
=> [dhd] Skip mountpoint /dev/usb-ffs/adb because it breaks MTP.

droid-hal-device.inc
Previous solution never worked, as it's done in %install, where
%{android_root} no longer exists
=> [dhd] Fix PARANOID_NETWORK automation

droid-hal-device.inc
This sed command from @mlehtima fixes the issue on Sonys scorpion, that /tmp has the wrong permissions. Which had effects in the peoples and phone applications.
[source of the sed command ](http://www.merproject.org/logs/%23sailfishos-porters/%23sailfishos-porters.2016-10-01.log.html#t2016-10-01T16:52:18)
=>  [dhd] allow People application to save contacts, let Phone application access contacts, call list

helpers/pack_source_droidmedia-localbuild.sh
This change allows to use external droidmedia version, but retains backward compatibility with defaulting to 0.0.0
For packaking local build of droidmedia, following commands from HADK needs to be revised to use version from droidmedia repository tag:
```
cd $ANDROID_ROOT
DROIDMEDIA_VERSION=$(git --git-dir external/droidmedia/.git describe --tags | sed -r "s/\-/\+/g")
rpm/dhd/helpers/pack_source_droidmedia-localbuild.sh $DROIDMEDIA_VERSION
mkdir -p hybris/mw/droidmedia-localbuild/rpm
cp rpm/dhd/helpers/droidmedia-localbuild.spec hybris/mw/droidmedia-localbuild/rpm/droidmedia.spec
sed -ie "s/0.0.0/$DROIDMEDIA_VERSION/" hybris/mw/droidmedia-localbuild/rpm/droidmedia.spec
mv hybris/mw/droidmedia-$DROIDMEDIA_VERSION.tgz hybris/mw/droidmedia-localbuild
rpm/dhd/helpers/build_packages.sh …
```
=> [helpers] Allow using specific version for droidmedia-localbuild

helpers/audioflingerglue-localbuild.spec, helpers/pack_source_audioflingerglue-localbuild.sh
update audioflingerglue-localbuild to match changes, fixing the lib path to allow for 64bit builds
=> fix audioflingerglue-localbuild

droid-hal-device.inc
Since Android 7, build will create .toc files of all libraries. Toc is
txt file and include library symbol names. When devel package includes
those files OBS will result rpmlint error.
=> Remove *.so.toc files from devel package.

droid-hal-device.inc
Some bluetooth devices might use bluetooth user permission
and that is why user needs to be on that group.
=> Add user to bluetooth group by default.

helpers/build_packages.sh
Required for https://github.com/mer-hybris/droid-hal-version/pull/10
=> [build_packages] Build native vibrator middleware by default.

helpers/build_packages.sh, helpers/util.sh
New libzypp checks package signatures by default, and locally build packages are unsigned.
=> [zypper] Allow unsigned package installation from local repos and files. JB#42244

droid-hal-device.inc
Android 8 based devices without vendor partition place these files under /system/vendor.
=> [dhd] Search for fstab and ueventd.rc files also under system/vendor.

helpers/build_packages.sh
Libgbinder-radio is needed dependency for ofono-ril-binder-plugin.
=> Build libgbinder-radio.

helpers/build_packages.sh, helpers/util.sh
Allow supplying multiple `.spec` files
Instead of relying on positional arguments, allow the following:
- `-u` for git URL
- `-b` for branch name
- `-s` for spec file. Can be supplied multiple times
Using named arguments for calling `buildmw()` makes the whole thing more readable.
Use full URLs as well for better readability.
Using `$@` instead of `$1` means all arguments are iterated over when looping `$SPECS`
=> Rework buildmw() to use named arguments

helpers/build_packages.sh, helpers/util.sh
Add an option to explicitly don't instal a pkg while deploying it.
This allows to build and deploy pkgs where not every sub-pkg is to
be installed. For example like updating ofono where there's a default
config, that conflicts with the device config or droid-vendor where
setcap fails.
=> [helpers] Add option to explicitly don't install a pkg

helpers/build_bootimg_packages.sh
This helps with `droid-hal-img-boot` packages that need `yamui`, `e2fsprogs` and more, c.f. [hybris-initrd/droid-hal-device-img-boot.inc](https://github.com/mer-hybris/hybris-initrd/blob/ae58855e8bf911bbf6836e351da1677ec6f49129/droid-hal-device-img-boot.inc#L67-L74)
Didn't want to clutter `build_packages.sh` any further so it's split out into another script.
Dependent on #205 because it uses the named-arg `buildmw -u $URL -s $SPEC` syntax.
=> Add build_bootimg helper script

helpers/pack_source_audioflingerglue-localbuild.sh, helpers/pack_source_droidmedia-localbuild.sh
If no `$HABUILD_DEVICE` is defined, fall back to `$DEVICE`.
Example:
`$HABUILD_DEVICE=kagura`
`$DEVICE=f8331`
Android's build system will create `$ANDROID_ROOT/out/target/product/kagura`
Any opinions on trying to use `$FAMILY` to detect whether to use `$HABUILD_DEVICE` like in https://github.com/mer-hybris/droid-hal-device/blob/31c62347e952ff7ac2da79c29020e92ed8a56008/helpers/build_packages.sh#L134-L138 ?
=> helpers: Try to use $HABUILD_DEVICE for droidmedia and audioflingerglue

helpers/audioflingerglue-localbuild.spec, helpers/pack_source_audioflingerglue-localbuild.sh
Support setting the version of the audiofingerglue tar archive in dhd
like droidmedia.
=> [helpers] Allow set $pkg ver in audiofingerglue tar. Fixes MER#2018

droid-hal-device.inc, helpers/pack_source_audioflingerglue-localbuild.sh, helpers/pack_source_droidmedia-localbuild.sh
Remove `droidmedia` and `audioflingerglue` libs+bins from `$RPM_BUILD_ROOT/%{_libexecdir}` when building `droid-hal-device`, thus preventing clashing files with the `localbuild` variants.
This commit simply moves the logic around so that one can build all `HABUILD_SDK` tasks at once and then not have to worry about the order of execution for building `droid-hal` and `droidmedia/audioflingerglue-localbuild`.
Without this commit, one has to re-build the `droidmedia/audioflingerglue` libs in the `HABUILD_SDK` every time before packaging the `localbuild` variants.
=> dhd: Omit droidmedia+audioflingerglue from libexec

droid-hal-device.inc
Lower than Android 8 version mkbootimg makefile needs gnu99 flag to build properly.
=> Add gnu99 flag to build mkbootimg.

droid-hal-device.inc
[dhd] Exclude bin folder when copying Android root files. JB#46519
=> dhd: Exclude bin folder when copying Android root files.

droid-hal-device.inc
Some legacy devices use system/vendor/lib/modules as module location.
=> dhd: Copy kernel modules from system/vendor/lib/modules. MER#2054

droid-hal-device.inc
Source0 have to be in main spec file, not in included
one. Without this OBS promotions does not work properly.
=> [dhd] Remove Source0 from droid_src_build. JB#46848

droid-hal-device.inc
[dhd] Add Source0 for droid_src_build. JB#46848
Source0 was moved to main spec file but version is not known in
that phase on promotion checks. Re-introduce it back after
version is known.
=> dhd: Add Source0 for droid_src_build.

helpers/build_packages.sh
No longer needed in adaptations, hwcomposer-plugin should be used instead.
=> helpers: obsolete qt5-qpa-surfaceflinger-plugin

helpers/build_packages.sh, helpers/util.sh
- Use builtin $PWD
- Fix quoting in case path names contain spaces [SC2046]
- Remove useless function keyword 
- Remove useless true just return zero
- Use if directly, using test is redundant
- Remove yesnoal, add --build-all
- Quote ${BUILDSPEC_FILE[@]} to avoid resplitting of elements
- Don't use bash == on posix test [] and use [] everywhere
=> [dhd] Helpers cleanup

droid-hal-device.inc
When audio group is removed and re-created pulse user is dropped from audio group.
To make sure that PulseAudio system mode is functional create all required users
and groups here as well. Remove this workaround when the group handling is a bit
more sane.
=> Add a workaround for system mode PulseAudio.

helpers/build_packages.sh
This issue is a very recent issue introduced by PR #247, which added support for building loop images. The grep command however wasn't implemented properly and thus it doesn't detect `droid-hal-*-kernel-modules` in patterns like it should due to a syntactical issue.
This results in the assumption that a loop image shall be built and fails installing each package with `installing package X needs Y MB on the / filesystem` spammed on screen.
The exact same behavior has been seen by me and @nit-in already, but I'm pretty sure it would affect others too that do (local) mic builds after a dhd submodule update.
My solution simply fixes this mistake by using grep in extended regex mode while utilizing a logical or for the 2 different `DEVICE` values inside regular brackets.
=> helpers: Fix broken fs image building

droid-hal-device.inc
[dhd] droid-hal-users should provide hardware-adaptation-setup. JB#47910
=> dhd: droid-hal-users should provide hardware-adaptation-setup.

droid-hal-device.inc
[dhd] add support for one extra init rc, which can be used to provide info from the adaptation to sfos. JB#48187
=> dhd: add support for one extra init rc, which can be used to provide info from the adaptation to sfos

droid-hal-device.inc
Instead of adding default user to hardware adaptation required groups
during package install store the groups to filesystem for later access.
Then when new user is created this list can be consulted for the correct
groups the user needs to be in.
=> Store user required groups instead of adding immediately.

helpers/build_packages.sh
if patterns have different name or just missing, then build_packages.sh hangs.
pattern_lookup is empty and as a result grep execution does not receive file as
a parameter and infinitely waits for input from stdin.
=> [helpers] Fix hang build_packages.sh on missing patterns. Fixes JB#49401

helpers/build_packages.sh
With this devices that don't have differing `DEVICE` and `HABUILD_DEVICE` variable contents in the context of `build_packages.sh` (a.k.a most community ported devices) can be built for again locally as non-unique outputs are parsed out from `pattern_lookup`. [Quoting the pattern_lookup strings](https://github.com/mer-hybris/droid-hal-device/commit/211682d86c01c86304f861e798f4f2cfcfe544b2) made it impossible to grep more than one file at once.
The grep command failed to find a match on all of the instances where `pattern_lookup` was used as it was trying to exec `grep "pattern" "file1 file1"` and that simply doesn't work.
=> helpers: Filter out non-unique files in pattern_lookup

droid-hal-device.inc
this problem happens if Android version is <= 6 and there is file
hybris_extras.rc in system/etc/init. It is introduced by commit
1fb8758dafa5 ("dhd: add support for one extra init rc, which can be
used to provide info from the adaptation to sfos")
In this case build_packages.sh fails with following error:
$ rpm/dhd/helpers/build_packages.sh
+ '[' 4 -ge 7 ']'
+ echo ''
+ '[' -f ./out/target/product/hammerhead/system/etc/init/hybris_extras.rc ']'
+ cp -a ./out/target/product/hammerhead/system/etc/init/hybris_extras.rc /media/data/port/android/installroot/usr/libexec/droid-hybris/system/etc/init/
cp: cannot create regular file `/media/data/port/android/installroot/usr/libexec/droid-hybris/system/etc/init/': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.SrHvD1 …
=> dhd: Fix Android 6 <= based builds

helpers/build_packages.sh
Merge with https://github.com/mer-hybris/droid-hal-configs/pull/183
=> helpers: fix build when bluez5 is not in target

helpers/build_packages.sh, helpers/util.sh
This is useful when building packages with multiple .spec files at
different times, and you wand all packages to exist in the local
repository.
=> helpers: Add option to not delete existing packages when adding to repo

helpers/audioflingerglue-localbuild.spec, helpers/build_packages.sh, helpers/droidmedia-localbuild.spec
[helpers] Look for droidmedia and audioflingerglue builds only for current device.
This helps when doing local builds for more than one device using the same Android source tree.
=> helpers: Look for droidmedia and audioflingerglue builds only for current device.

helpers/build_packages.sh
[helpers] Remove not needed vibrator packages from build_packages.sh
These packages have been available in Jolla repos for a long time, no need to build them here.
=> helpers: Remove not needed vibrator packages from build_packages.sh

droid-hal-device.inc
mkbootimg is mkbootimg.py in later versions
=> dhd: mkbootimg is mkbootimg.py in later versions

droid-hal-device.inc
Instead of pointed makeudev to paths that maybe not exist and filter
with ls, use find and filter directly.
This also fixes cases where for example there's no /system/vendor and just
/vendor (which is enforced with later android versions).
=> dhd: Use find to point makeudev to uventd rcs instead of paths

helpers/img2simg.mk, helpers/simg2img.mk
The standard flag c++0x is depreacted in gcc, use recommended c++11 or
gnu++11. This also fixes android 10 builds because libsparse is converted to
c++ typeof starting with android 10/platform-tools 29 and use c
typeof (which is a gnu extension).
=> helpers: Don't use deprecated std c++0x

helpers/build_packages.sh, helpers/util.sh
@Thaodan implemented ability to instruct mb2 to skip generating version from git tag when such is not available (droidmedia-localbuild) or invalid, this way getting rid of couple of old hacks.
Another feature is to recover tags from shallow clones or if working offline, inform the user about it.
=> Improve package version handling

droid-hal-device.inc
For example, this is can be used to build platform specific binary files from source code, generate flashing scripts and pack them into separate packages. In some cases extra source need and they can be supplied using submodules.
=> Add possibility to customize and build extra subpackages in droid-hal. Contributes to JB#52099

helpers/build_packages.sh
[helpers] Always build libglibutil required by libgbinder.
=> helpers: Always build libglibutil required by libgbinder.

helpers/audioflingerglue-localbuild.spec, helpers/build_packages.sh, helpers/pack_source_audioflingerglue-localbuild.sh
This fix audioflingerglue build on aarch64 target, without this patch afglue build log:
```
Processing files: audioflingerglue-0.0.13-1.armv7hl
Provides: audioflingerglue = 0.0.13-1 audioflingerglue(aarch-64) = 0.0.13-1
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Processing files: audioflingerglue-devel-0.0.13-1.noarch
Provides: audioflingerglue-devel = 0.0.13-1
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/bird/work/hadk_14.1/hybris/mw/audioflingerglue-localbuild/installroot
Wrote: /home/bird/work/hadk_14.1/hybris/mw/audioflingerglue-localbuild/RPMS/audioflingerg …
```
=> [audioflingerglue] Fix afglue build on aarch64 target

droid-hal-device.inc, helpers/build_packages.sh
[dhd] Move droid headers to /usr/include
=> dhd: Move droid headers to /usr/include

helpers/build_packages.sh
Fixes the following:
```
$ rpm/dhd/helpers/build_packages.sh --mw
...
* Building of libncicore finished successfully 
* Source code directory doesn't exist, cloning repository 
* pulling updates... 
* No spec file for package building specified, building all I can find. 
* Building rpm/libnciplugin.spec 
Cloning into 'libnciplugin'...
Already up to date.
No provider of 'pkgconfig(nfcd-plugin) >= 1.1.0' found.
Setting version: 1.1.0
hostname: Unknown host
No journal files were found.
error: Failed build dependencies:
pkgconfig(libncicore) >= 1.1.13 is needed by libnciplugin-1.1.0-0.aarch64
pkgconfig(nfcd-plugin) >= 1.1.0 is needed by libnciplugin-1.1.0-0.aarch64
Building target platforms: aarch64-meego-linux-gnu
Building for target aarch64-meego-linux-gnu
No journal files were found. …
```
=> helpers: Build nfcd from git to avoid breaking libnciplugin git build

helpers/build_packages.sh
Since there's no `adaptation-community-common` repo for community `aarch64` ports for now and it was dropped from ks, the `sed` command did not add the `droid-local-repo` anymore to ks causing `mic` image build failure.
=> dhd: Fix community aarch64 local builds

helpers/build_packages.sh
These are needed by increasing number of devices.
Those devices that do not need, will simply not mention these in the patterns.
=> Always build dummy_netd, yamuisplash, and sailfish-connman-plugin-suspend

droid-hal-device.inc
[dhd] Don't terminate build if files are missing build ids. JB#52914
=> dhd: Don't terminate build if files are missing build ids.

droid-hal-device.inc
[dhd] remove note about aarch64 since there is an aarch64 target now.
[dhd] lib{c,dl,m}.so may be in alternate locations.
=> dhd: remove note about aarch64 and fix apex path.

droid-hal-device.inc
The / was missing in /sys/fs/bpf.
=> dhd: Fix typo in default skip %{makefstab_skip_entries}

helpers/build_packages.sh
Remove this line when audiosystem-passthrough-devel gets added to the public hw:common.
=> helpers: fix local build of pulseaudio-modules-droid-hidl

helpers/build_packages.sh, helpers/util.sh
Fixes the error after installing bluez5 packages:
`cp: cannot overwrite directory '/srv/mer/targets/$VENDOR-$DEVICE-$PORT_ARCH.default/etc/bluetooth' with non-directory`
=> Fix SDK snapshot update

helpers/util.sh
This happens when the localbuild of droid-hal-img-boot applies
the fix by replacing busybox's cpio with the GNU/cpio.
Can be removed for the next update after 4.3.0.x
=> helpers: work around busybox-cpio replacement symlink clash

droid-hal-device.inc
Run the Android build commands with set -e/errexit so that in case on
them fails the shell directly exits instead of silently continuing.
=> dhd: Immediately fail Android builds on OBS if a command fails

droid-hal-device.inc
We did call sh to run droid build which would have been fine, but since
Androids envsetup requires bash or zsh we call bash so lunch works.
[dhd] Call bash instead of sh with ubu-chroot. JB#57846
=> dhd: Call bash instead of sh with ubu-chroot

droid-hal-device.inc
[dhd] Do not install /sbin/mkdosfs binary. JB#58522
Some Android build compile /sbin/mkdosfs binary which is
conflicting to busybox-symlinks-dosfstools in image building phase.
=> dhd: Do not install /sbin/mkdosfs binary.

droid-hal-device.inc, helpers/build_packages.sh, helpers/util.sh
Disable checks from builds. Add missing --allow-unsigned-rpm to some install commands.
=> Fix checking kernel version when dtbo.img has been built

helpers/droidmedia-localbuild.spec, helpers/pack_source_droidmedia-localbuild.sh
Fixes builds for 4.4.0 with older droidmedia.
=> droidmedia-localbuild: Package init files only if they exist

droid-hal-device.inc, helpers/audioflingerglue-localbuild.spec, helpers/build_packages.sh, helpers/droidmedia-localbuild.spec, helpers/extract-headers.sh, helpers/img2simg.mk, helpers/makefile, helpers/simg2img.mk, helpers/util.sh
Add Android 12 and 13 support.
Install ccache to target.
Do not build kf5bluezqt-bluez4.
Remove useless Group tags from audioflinger and droidmedia spec files.
Fix packaging init files in droidmedia-localbuild spec.
=> Android 12 and 13 support and various fixes

droid-hal-device.inc
Always overwrite dtbo file list to prevent warnings during build
[dhd] Fix handling files for Android versions older than 13
=> dhd: Fix handling files for Android versions older than 13
