mer-hybris/droid-hal-device

- device-asus-flo-configs/var/lib/environment/compositor/droid-hal-device.conf
- droid-hal-flo.spec
- patterns/flo/jolla-configuration-flo.yaml
- patterns/flo/jolla-configuration-sfe.yaml
- patterns/flo/jolla-hw-adaptation-flo.yaml
- patterns/flo/jolla-hw-adaptation-hybris-droid-vibrator.yaml
- patterns/flo/jolla-hw-adaptation-hybris.yaml
Change-Id: I8fb8cfcf49fbfd9dfab763c32d5474a500f29fa6
> Add asus flo (Nexus 7 2013)

- droid-hal-device.inc
- droid-hal-hammerhead.spec
- patterns/hammerhead/jolla-hw-adaptation-hammerhead.yaml
Merge together with https://github.com/foolab/gst-droid/pull/2
> Revert gstdroid hack

- patterns/hammerhead/jolla-hw-adaptation-hammerhead.yaml
- patterns/templates/jolla-hw-adaptation-@DEVICE@.yaml
Merge with https://github.com/mer-hybris/droid-hal-configs/pull/13 counterpart, as SFE community is still using monolithic dhd packaging. Split modular packaging is WIP
> Enable usb moded

- droid-hal-device.inc
Signed-off-by: Marko Saukko <marko.saukko@jolla.com>
> Allow having custom img-boot package.

- droid-hal-device.inc
should be t instead of t with stroke
> Fixed comment typo

- droid-hal-device.inc
droid-hal-configs commit:
https://github.com/mer-hybris/droid-hal-configs/commit/5359b6791f0e47a617c9eae4177c320d303e7f73
> Fix droid-config dependency to droid-config-flashing package

- helpers/build_packages.sh
- helpers/util.sh
Useful for e.g. droidmedia-localbuild et al.
> [build_package] Add a simple build and deploy

- droid-hal-device.inc
Adding nemo to inet group brings internet back to Sailfish OS.
> [dhd] Android 5+ rild requires PARANOID_NETWORK

- helpers/build_packages.sh
- helpers/fix_dangling_adaptation-community_repo.sh
- helpers/util.sh
Get this in after merging https://github.com/mer-hybris/community-adaptation/pull/1
> Don't add "adaptation-community" repo in local builds

- droid-hal-device.inc
Will need this merged too to take effect: https://github.com/mer-hybris/hybris-boot/pull/110
> Check if hybris-boot is being used as submodule or not

- droid-hal-device.inc
QCOM_BSP and adding nemo to inet group have been broken since two weeks ago, this is the fix and apologies 🙂
> Fix Android version handling

- droid-hal-device.inc
- helpers/build_packages.sh
- helpers/extract-headers.sh
- helpers/makefile
WIP: Missing symlinking of init*.rc files.
> [dhd] Add support for Android 7 based builds.

- droid-hal-device.inc
- helpers/build_packages.sh
Instructions will be relevant when https://github.com/mer-hybris/libhybris/pull/35 is merged
> For new libhybris

- droid-hal-device.inc
- helpers/build_packages.sh
- helpers/extract-headers.sh
- helpers/img2simg.mk
- helpers/makefile
- helpers/makefstab
- helpers/simg2img.mk
- helpers/usergroupgen.c
- helpers/util.sh
Adapt for new paths and changes in android 8.
Co-authored-by: Franz-Josef Haider <franz.haider@jolla.com>
> [dhd] Fix build for Android 8.

- helpers/build_packages.sh
@sledges sorry, this slipped in with the named-args PR.
> build_packages.sh: Fix typo in URL

- droid-hal-device.inc
[dhd] Add ability to modify dhd git submodule path.
> dhd: Add ability to modify dhd git submodule path.

- droid-hal-device.inc
[dhd] Allow using dhd_sources for local and obs builds. JB#46848
> dhd: Allow using dhd_sources for local and obs builds.

- droid-hal-device.inc
[dhd] Provide hardware-adaptation-setup from droid-hal. JB#47549
> dhd: Provide hardware-adaptation-setup from droid-hal.

- helpers/build_bootimg_packages.sh
- helpers/build_packages.sh
- helpers/util.sh
This means no questions will be asked during a build invoked without cmdline
switches.
> helpers: ask to build each package only when --mw is in cmdline

- helpers/build_packages.sh
- helpers/util.sh
Check for manifest.xml under $ANDROID_ROOT/.repo (or in parent dirs) and build mw packages from there, if at least one path is under hybris/mw.
> helpers: build mw packages if they are in manifest.xml

- helpers/build_packages.sh
This will require https://github.com/mer-hybris/hybris-boot/pull/175 and a change in the HADK doc:
```diff
-  make -j$(nproc --all) hybris-hal
+  make -j$(nproc --all) hybris-hal droidmedia audioflingerglue
```
Note, `audioflingerglue` make target would not be needed for the Android 9 builds with `pulseaudio-modules-droid-hidl`
> helpers: build gst-droid, pulseaudio droid glue, and their deps

- .gitignore
- droid-hal-device.inc
- helpers/usergroupgen.c
@ballock I couldn't add you as a reviewer here but please do provide input if you have some.
Only tested on 1 device so far.
> Simplify droid-hal user and group creation

- droid-hal-device.inc
[dhd] Simplify build flavour reading. Fixes JB#48212
> dhd: Simplify build flavour reading.

- helpers/util.sh
[helpers] Fix droidmedia and audioflingerglue local builds in online mode
> helpers: Fix droidmedia and audioflingerglue local builds in online mode

- helpers/build_packages.sh
ofono-ril-binder-plugin requires it
> Build libncicore for Android 8

- helpers/build_packages.sh
Merge with https://github.com/mer-hybris/droid-hal-configs/pull/184
> helpers: replace audioflingerglue with audiosystem-passthrough

- helpers/build_bootimg_packages.sh
- helpers/build_packages.sh
- helpers/util.sh
Merge with https://github.com/mer-hybris/droid-hal-configs/pull/182
> simpler HADK

- droid-hal-device.inc
[dhd] Fix RPM version tag. JB#50383
> dhd: Fix RPM version tag.

- helpers/add_new_device.sh
- helpers/build_packages.sh
While still preserving the main Jolla Configuration @DEVICE@ pattern for backwards compatibility.
> helpers: patterns to meta-packages for new devices

- helpers/pack_source_droidmedia-localbuild.sh
[helpers] Look for droidmedia build only for current device.
> helpers: Look for droidmedia build only for current device.

- helpers/build_packages.sh
[Helpers] Include gmp-droid in build_packages --gg build. JB#50581
> helpers: include gmp-droid in build_packages --gg build.

- helpers/build_packages.sh
[helpers] Fix audioflingerglue local build.
> helpers: Fix audioflingerglue local build.

- droid-hal-device.inc
Ready for review/merging, all below have been merged:
~~https://github.com/mer-hybris/hybris-boot/pull/193~~
~~https://github.com/mer-hybris/droid-hal-device/pull/239~~
~~https://github.com/mer-hybris/droid-hal-device/pull/240~~
~~https://github.com/mer-hybris/droid-hal-device/pull/243~~
> dhd: Android 10 support

- droid-hal-device.inc
[android-10] Do not fail if apex folder already exists.
> android-10: Do not fail if apex folder already exists.

- helpers/build_packages.sh
[dhd] Fix detection of header location in local builds
> dhd: Fix detection of header location in local builds

- helpers/build_packages.sh
- helpers/util.sh
Merge together with https://github.com/mer-hybris/droid-hal-configs/pull/227
> patterns: remove yaml leftovers

- helpers/build_packages.sh
[helpers] Use github for middleware packages.
> helpers: Use github for middleware packages

- helpers/build_packages.sh
- helpers/droidmedia-localbuild.spec
This brings minimum SFOS version for ports to 4.3.0.
> Fix localbuilds

- droid-hal-device.inc
[dhd] Package patched apexd.rc for Android >= 12
> dhd: Package patched apexd.rc for Android >= 12

- droid-hal-device.inc
- helpers/build_packages.sh
- helpers/extract-headers.sh
Fix image builds for devel targets
> Add Android 14 support

- droid-hal-device.inc
[dhd] Remove whole odm folder instead of just its content
> dhd: Remove whole odm folder instead of just its content

- droid-hal-device.inc
[dhd] Allow having custom vendor_boot image
> dhd: Allow having custom vendor_boot image
